version: '3.8'

#MongoDb, Postgres, redis, Elasticsearch, RabbitMQ, Redis, Nginx, Nodejs, and Python
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    # volumes:
    #   - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
  redis:
    image: redis